USE `auth`;
INSERT IGNORE INTO `rbac_permissions` VALUES (1002, 'Command: .barber');
INSERT IGNORE INTO `rbac_permissions` VALUES (1003, 'Command: .castgroup');
INSERT IGNORE INTO `rbac_permissions` VALUES (1004, 'Command: .castscene');
INSERT IGNORE INTO `rbac_permissions` VALUES (1360, 'Command: .customnpc set displayid');
INSERT IGNORE INTO `rbac_permissions` VALUES (1361, 'Command: .customnpc set guild');
INSERT IGNORE INTO `rbac_permissions` VALUES (1362, 'Command: .customnpc set rank');
INSERT IGNORE INTO `rbac_permissions` VALUES (1363, 'Command: .customnpc set scale');
INSERT IGNORE INTO `rbac_permissions` VALUES (1364, 'Command: .customnpc set tameable');
INSERT IGNORE INTO `rbac_permissions` VALUES (1365, 'Command: .customnpc remove variation');
INSERT IGNORE INTO `rbac_permissions` VALUES (1398, 'Command: .gobject set scale');
INSERT IGNORE INTO `rbac_permissions` VALUES (1589, 'Command: .npc set scale');
INSERT IGNORE INTO `rbac_permissions` VALUES (2101, 'Command: .customnpc create');
INSERT IGNORE INTO `rbac_permissions` VALUES (2102, 'Command: .customnpc spawn');
INSERT IGNORE INTO `rbac_permissions` VALUES (2103, 'Command: .customnpc set displayname');
INSERT IGNORE INTO `rbac_permissions` VALUES (2104, 'Command: .customnpc set face');
INSERT IGNORE INTO `rbac_permissions` VALUES (2105, 'Command: .customnpc set gender');
INSERT IGNORE INTO `rbac_permissions` VALUES (2106, 'Command: .customnpc set race');
INSERT IGNORE INTO `rbac_permissions` VALUES (2107, 'Command: .customnpc set subname');
INSERT IGNORE INTO `rbac_permissions` VALUES (2108, 'Command: .customnpc equip armor');
INSERT IGNORE INTO `rbac_permissions` VALUES (2109, 'Command: .customnpc equip left');
INSERT IGNORE INTO `rbac_permissions` VALUES (2110, 'Command: .customnpc equip ranged');
INSERT IGNORE INTO `rbac_permissions` VALUES (2111, 'Command: .customnpc equip right');
INSERT IGNORE INTO `rbac_permissions` VALUES (2112, 'Command: .customnpc delete');
INSERT IGNORE INTO `rbac_permissions` VALUES (3000, 'Command: .wmorph');
INSERT IGNORE INTO `rbac_permissions` VALUES (3001, 'Command: .wscale');
INSERT IGNORE INTO `rbac_permissions` VALUES (3002, 'Command: .remorph');
INSERT IGNORE INTO `rbac_permissions` VALUES (3004, 'Command: .gob visible');
INSERT IGNORE INTO `rbac_permissions` VALUES (1005, 'Command: .typing on');
INSERT IGNORE INTO `rbac_permissions` VALUES (1006, 'Command: .typing off');
INSERT IGNORE INTO `rbac_permissions` VALUES (1022, 'Command: .settime');
INSERT IGNORE INTO `rbac_permissions` VALUES (1008, 'Command: .disp');
INSERT IGNORE INTO `rbac_permissions` VALUES (1009, 'Command: .disp head');
INSERT IGNORE INTO `rbac_permissions` VALUES (1010, 'Command: .disp shoulders');
INSERT IGNORE INTO `rbac_permissions` VALUES (1011, 'Command: .disp shirt');
INSERT IGNORE INTO `rbac_permissions` VALUES (1012, 'Command: .disp chest');
INSERT IGNORE INTO `rbac_permissions` VALUES (1013, 'Command: .disp waist'); 
INSERT IGNORE INTO `rbac_permissions` VALUES (1014, 'Command: .disp legs'); 
INSERT IGNORE INTO `rbac_permissions` VALUES (1015, 'Command: .disp feet'); 
INSERT IGNORE INTO `rbac_permissions` VALUES (1016, 'Command: .disp wrists'); 
INSERT IGNORE INTO `rbac_permissions` VALUES (1017, 'Command: .disp hands'); 
INSERT IGNORE INTO `rbac_permissions` VALUES (1018, 'Command: .disp back'); 
INSERT IGNORE INTO `rbac_permissions` VALUES (1019, 'Command: .disp tabard'); 
INSERT IGNORE INTO `rbac_permissions` VALUES (1020, 'Command: .disp mainhand'); 
INSERT IGNORE INTO `rbac_permissions` VALUES (1021, 'Command: .disp offhand');

INSERT IGNORE INTO `rbac_linked_permissions` VALUES (199, 1002);
INSERT IGNORE INTO `rbac_linked_permissions` VALUES (193, 1003);
INSERT IGNORE INTO `rbac_linked_permissions` VALUES (193, 1004);
INSERT IGNORE INTO `rbac_linked_permissions` VALUES (193, 1360);
INSERT IGNORE INTO `rbac_linked_permissions` VALUES (193, 1361);
INSERT IGNORE INTO `rbac_linked_permissions` VALUES (193, 1362);
INSERT IGNORE INTO `rbac_linked_permissions` VALUES (193, 1363);
INSERT IGNORE INTO `rbac_linked_permissions` VALUES (193, 1364);
INSERT IGNORE INTO `rbac_linked_permissions` VALUES (193, 1365);
INSERT IGNORE INTO `rbac_linked_permissions` VALUES (193, 1398);
INSERT IGNORE INTO `rbac_linked_permissions` VALUES (193, 1589);
INSERT IGNORE INTO `rbac_linked_permissions` VALUES (193, 2101);
INSERT IGNORE INTO `rbac_linked_permissions` VALUES (193, 2102);
INSERT IGNORE INTO `rbac_linked_permissions` VALUES (193, 2103);
INSERT IGNORE INTO `rbac_linked_permissions` VALUES (193, 2104);
INSERT IGNORE INTO `rbac_linked_permissions` VALUES (193, 2105);
INSERT IGNORE INTO `rbac_linked_permissions` VALUES (193, 2106);
INSERT IGNORE INTO `rbac_linked_permissions` VALUES (193, 2107);
INSERT IGNORE INTO `rbac_linked_permissions` VALUES (193, 2108);
INSERT IGNORE INTO `rbac_linked_permissions` VALUES (193, 2109);
INSERT IGNORE INTO `rbac_linked_permissions` VALUES (193, 2110);
INSERT IGNORE INTO `rbac_linked_permissions` VALUES (193, 2111);
INSERT IGNORE INTO `rbac_linked_permissions` VALUES (193, 2112);
INSERT IGNORE INTO `rbac_linked_permissions` VALUES (193, 3004);
INSERT IGNORE INTO `rbac_linked_permissions` VALUES (199, 3000);
INSERT IGNORE INTO `rbac_linked_permissions` VALUES (199, 3001);
INSERT IGNORE INTO `rbac_linked_permissions` VALUES (199, 3002);
INSERT IGNORE INTO `rbac_linked_permissions` VALUES (193, 1022);
INSERT IGNORE INTO `rbac_linked_permissions` VALUES (199, 1005);
INSERT IGNORE INTO `rbac_linked_permissions` VALUES (199, 1006);
INSERT IGNORE INTO `rbac_linked_permissions` VALUES (199, 1008);
INSERT IGNORE INTO `rbac_linked_permissions` VALUES (199, 1009);
INSERT IGNORE INTO `rbac_linked_permissions` VALUES (199, 1010);
INSERT IGNORE INTO `rbac_linked_permissions` VALUES (199, 1011);
INSERT IGNORE INTO `rbac_linked_permissions` VALUES (199, 1012);
INSERT IGNORE INTO `rbac_linked_permissions` VALUES (199, 1013);
INSERT IGNORE INTO `rbac_linked_permissions` VALUES (199, 1014);
INSERT IGNORE INTO `rbac_linked_permissions` VALUES (199, 1015);
INSERT IGNORE INTO `rbac_linked_permissions` VALUES (199, 1016);
INSERT IGNORE INTO `rbac_linked_permissions` VALUES (199, 1017);
INSERT IGNORE INTO `rbac_linked_permissions` VALUES (199, 1018);
INSERT IGNORE INTO `rbac_linked_permissions` VALUES (199, 1019);
INSERT IGNORE INTO `rbac_linked_permissions` VALUES (199, 1020);
INSERT IGNORE INTO `rbac_linked_permissions` VALUES (199, 1021);

INSERT IGNORE INTO `rbac_permissions` VALUES (1007, 'Command: .typing');
INSERT IGNORE INTO `rbac_permissions` VALUES (2004, 'Command: .blackmarket');
INSERT IGNORE INTO `rbac_permissions` VALUES (2005, 'Command: .blackmarket set duration');
INSERT IGNORE INTO `rbac_permissions` VALUES (2113, 'Command: .customnpc unequip armor');
INSERT IGNORE INTO `rbac_permissions` VALUES (2114, 'Command: .customnpc unequip left');
INSERT IGNORE INTO `rbac_permissions` VALUES (2115, 'Command: .customnpc unequip ranged');
INSERT IGNORE INTO `rbac_permissions` VALUES (2116, 'Command: .customnpc unequip right');
INSERT IGNORE INTO `rbac_permissions` VALUES (3005, 'Command: .scenario all');
INSERT IGNORE INTO `rbac_permissions` VALUES (3006, 'Command: .npc set aura');
INSERT IGNORE INTO `rbac_permissions` VALUES (3007, 'Command: .outfit');
INSERT IGNORE INTO `rbac_permissions` VALUES (3008, 'Command: .comp');
INSERT IGNORE INTO `rbac_permissions` VALUES (3009, 'Command: .maxrep');
INSERT IGNORE INTO `rbac_permissions` VALUES (3010, 'Command: .maxtitles');
INSERT IGNORE INTO `rbac_permissions` VALUES (3011, 'Command: .maxachieve');
INSERT IGNORE INTO `rbac_linked_permissions` VALUES (199, 1007);
INSERT IGNORE INTO `rbac_linked_permissions` VALUES (193, 2004);
INSERT IGNORE INTO `rbac_linked_permissions` VALUES (193, 2005);
INSERT IGNORE INTO `rbac_linked_permissions` VALUES (193, 2113);
INSERT IGNORE INTO `rbac_linked_permissions` VALUES (193, 2114);
INSERT IGNORE INTO `rbac_linked_permissions` VALUES (193, 2115);
INSERT IGNORE INTO `rbac_linked_permissions` VALUES (193, 2116);
INSERT IGNORE INTO `rbac_linked_permissions` VALUES (193, 3005);
INSERT IGNORE INTO `rbac_linked_permissions` VALUES (193, 3006);
INSERT IGNORE INTO `rbac_linked_permissions` VALUES (193, 3007);
INSERT IGNORE INTO `rbac_linked_permissions` VALUES (193, 3008);
INSERT IGNORE INTO `rbac_linked_permissions` VALUES (193, 3009);
INSERT IGNORE INTO `rbac_linked_permissions` VALUES (193, 3010);
INSERT IGNORE INTO `rbac_linked_permissions` VALUES (193, 3011);

INSERT IGNORE INTO `rbac_default_permissions` (`secId`, `permissionId`) VALUES
(0, 3008);