CREATE TABLE IF NOT EXISTS `custom_solocraft_character_stats` (
  `GUID` BIGINT UNSIGNED NOT NULL,
  `Difficulty` FLOAT NOT NULL DEFAULT 0,
  `GroupSize` INT UNSIGNED NOT NULL DEFAULT 1,
  `SpellPower` INT UNSIGNED NOT NULL DEFAULT 0,
  `Stats` FLOAT NOT NULL DEFAULT 1.0,
  PRIMARY KEY (`GUID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;