-- NPC flag fixes: add missing npcflag bits based on Wowhead role data
-- Generated by cross_ref_npc_flags.py
-- Source: Wowhead raw NPC JSON (219K files) -> subtitle role detection -> DB cross-reference
--
-- APPLIED: 2,265 active NPC fixes (trainer, vendor, flight_master, innkeeper,
--          stable_master, banker, auctioneer, repair flags)
-- REMAINING: 47 entries on [UNUSED]/[PH]/DEPRECATED/Test NPCs (commented out below)
--
-- Uses bitwise OR so operations are idempotent
-- Safe to re-run: OR with existing flags is a no-op if already set
USE `world`;
-- ============================================================================
-- REMAINING: Unused/test NPCs with missing flags (informational, not applied)
-- These are all [UNUSED], [PH], DEPRECATED, or test entries
-- ============================================================================

-- [UNUSED] Grall Twomoons [354] subtitle="Shaman Trainer" - missing trainer(16)
-- UPDATE creature_template SET npcflag = npcflag | 16 WHERE entry = 354;

-- [UNUSED] Brannon Aybara (TEMP) [897] subtitle="Hunter Trainer" - missing trainer(16)
-- UPDATE creature_template SET npcflag = npcflag | 16 WHERE entry = 897;

-- [UNUSED] [PH] Berail Spiritwhisper [919] subtitle="Shaman Trainer *Temp*" - missing trainer(16)
-- UPDATE creature_template SET npcflag = npcflag | 16 WHERE entry = 919;

-- [UNUSED] Lexin Haze [1230] subtitle="Warlock Trainer *Temp*" - missing trainer(16)
-- UPDATE creature_template SET npcflag = npcflag | 16 WHERE entry = 1230;

-- World Warlock Trainer DEPRECATED [5039] subtitle="Warlock Trainer" - missing trainer(16)
-- UPDATE creature_template SET npcflag = npcflag | 16 WHERE entry = 5039;

-- [ph] Furion's Post Flight Master [35480] subtitle="Dragonhawk Master" - missing flight_master(8192)
-- UPDATE creature_template SET npcflag = npcflag | 8192 WHERE entry = 35480;

-- Romo's Test Hunter Trainer [36664] subtitle="Hunter Trainer" - missing trainer(16)
-- UPDATE creature_template SET npcflag = npcflag | 16 WHERE entry = 36664;

-- [PH] Jack of all Trades [46999] subtitle="Profession Trainer" - missing trainer(16)
-- UPDATE creature_template SET npcflag = npcflag | 16 WHERE entry = 46999;
