-- ============================================================
-- Creature Equipment Fixes: Remove invalid item IDs
-- Only for SPAWNED creatures (visible to players)
-- Generated by validate_equipment.py
-- Total fixes: 0
-- ============================================================

-- No fixes needed.
USE `world`;