-- ==========================================================================
-- npc_model_fixes.sql — Auto-generated by validate_models.py
-- Removes clearly invalid display IDs. Does NOT generate replacements.
-- ==========================================================================

USE `world`;
-- Section 2: Reset invalid per-spawn modelid overrides to 0
-- (reverts to creature_template_model default)

-- GUID 12729: creature 14881 (Spider) has invalid modelid=14952
UPDATE creature SET modelid=0 WHERE guid=12729 AND modelid=14952;

-- GUID 12730: creature 14881 (Spider) has invalid modelid=14952
UPDATE creature SET modelid=0 WHERE guid=12730 AND modelid=14952;

-- GUID 40054: creature 4304 (Scarlet Tracking Hound) has invalid modelid=2709
UPDATE creature SET modelid=0 WHERE guid=40054 AND modelid=2709;

-- GUID 40060: creature 4304 (Scarlet Tracking Hound) has invalid modelid=2709
UPDATE creature SET modelid=0 WHERE guid=40060 AND modelid=2709;

-- GUID 40070: creature 4304 (Scarlet Tracking Hound) has invalid modelid=2709
UPDATE creature SET modelid=0 WHERE guid=40070 AND modelid=2709;

-- GUID 40079: creature 4304 (Scarlet Tracking Hound) has invalid modelid=2709
UPDATE creature SET modelid=0 WHERE guid=40079 AND modelid=2709;

-- GUID 40089: creature 4304 (Scarlet Tracking Hound) has invalid modelid=2709
UPDATE creature SET modelid=0 WHERE guid=40089 AND modelid=2709;

-- GUID 40090: creature 4304 (Scarlet Tracking Hound) has invalid modelid=2709
UPDATE creature SET modelid=0 WHERE guid=40090 AND modelid=2709;

-- GUID 40091: creature 4304 (Scarlet Tracking Hound) has invalid modelid=2709
UPDATE creature SET modelid=0 WHERE guid=40091 AND modelid=2709;

-- GUID 53972: creature 12218 (Vile Larva) has invalid modelid=12346
UPDATE creature SET modelid=0 WHERE guid=53972 AND modelid=12346;

-- GUID 53973: creature 12218 (Vile Larva) has invalid modelid=12346
UPDATE creature SET modelid=0 WHERE guid=53973 AND modelid=12346;

-- GUID 53983: creature 12218 (Vile Larva) has invalid modelid=12346
UPDATE creature SET modelid=0 WHERE guid=53983 AND modelid=12346;

-- GUID 53984: creature 12218 (Vile Larva) has invalid modelid=12346
UPDATE creature SET modelid=0 WHERE guid=53984 AND modelid=12346;

-- GUID 53985: creature 12218 (Vile Larva) has invalid modelid=12346
UPDATE creature SET modelid=0 WHERE guid=53985 AND modelid=12346;

-- GUID 54007: creature 12218 (Vile Larva) has invalid modelid=12346
UPDATE creature SET modelid=0 WHERE guid=54007 AND modelid=12346;

-- GUID 54008: creature 12218 (Vile Larva) has invalid modelid=12346
UPDATE creature SET modelid=0 WHERE guid=54008 AND modelid=12346;

-- GUID 54012: creature 12218 (Vile Larva) has invalid modelid=12346
UPDATE creature SET modelid=0 WHERE guid=54012 AND modelid=12346;

-- GUID 54013: creature 12218 (Vile Larva) has invalid modelid=12346
UPDATE creature SET modelid=0 WHERE guid=54013 AND modelid=12346;

-- GUID 54061: creature 12218 (Vile Larva) has invalid modelid=12346
UPDATE creature SET modelid=0 WHERE guid=54061 AND modelid=12346;

-- GUID 54062: creature 12218 (Vile Larva) has invalid modelid=12346
UPDATE creature SET modelid=0 WHERE guid=54062 AND modelid=12346;

-- GUID 54063: creature 12218 (Vile Larva) has invalid modelid=12346
UPDATE creature SET modelid=0 WHERE guid=54063 AND modelid=12346;

-- GUID 54064: creature 12218 (Vile Larva) has invalid modelid=12346
UPDATE creature SET modelid=0 WHERE guid=54064 AND modelid=12346;

-- GUID 54065: creature 12218 (Vile Larva) has invalid modelid=12346
UPDATE creature SET modelid=0 WHERE guid=54065 AND modelid=12346;

-- GUID 54093: creature 12218 (Vile Larva) has invalid modelid=12346
UPDATE creature SET modelid=0 WHERE guid=54093 AND modelid=12346;

-- GUID 54095: creature 12218 (Vile Larva) has invalid modelid=12346
UPDATE creature SET modelid=0 WHERE guid=54095 AND modelid=12346;

-- GUID 54096: creature 12218 (Vile Larva) has invalid modelid=12346
UPDATE creature SET modelid=0 WHERE guid=54096 AND modelid=12346;

-- GUID 54099: creature 12218 (Vile Larva) has invalid modelid=12346
UPDATE creature SET modelid=0 WHERE guid=54099 AND modelid=12346;

-- GUID 54101: creature 12218 (Vile Larva) has invalid modelid=12346
UPDATE creature SET modelid=0 WHERE guid=54101 AND modelid=12346;

-- GUID 54102: creature 12218 (Vile Larva) has invalid modelid=12346
UPDATE creature SET modelid=0 WHERE guid=54102 AND modelid=12346;

-- GUID 54103: creature 12218 (Vile Larva) has invalid modelid=12346
UPDATE creature SET modelid=0 WHERE guid=54103 AND modelid=12346;

-- GUID 54104: creature 12218 (Vile Larva) has invalid modelid=12346
UPDATE creature SET modelid=0 WHERE guid=54104 AND modelid=12346;

-- GUID 54106: creature 12218 (Vile Larva) has invalid modelid=12346
UPDATE creature SET modelid=0 WHERE guid=54106 AND modelid=12346;

-- GUID 54122: creature 12218 (Vile Larva) has invalid modelid=12346
UPDATE creature SET modelid=0 WHERE guid=54122 AND modelid=12346;

-- GUID 54123: creature 12218 (Vile Larva) has invalid modelid=12346
UPDATE creature SET modelid=0 WHERE guid=54123 AND modelid=12346;

-- GUID 54133: creature 12218 (Vile Larva) has invalid modelid=12346
UPDATE creature SET modelid=0 WHERE guid=54133 AND modelid=12346;

-- GUID 54134: creature 12218 (Vile Larva) has invalid modelid=12346
UPDATE creature SET modelid=0 WHERE guid=54134 AND modelid=12346;

-- GUID 54135: creature 12218 (Vile Larva) has invalid modelid=12346
UPDATE creature SET modelid=0 WHERE guid=54135 AND modelid=12346;

-- GUID 54136: creature 12218 (Vile Larva) has invalid modelid=12346
UPDATE creature SET modelid=0 WHERE guid=54136 AND modelid=12346;

-- GUID 54148: creature 12218 (Vile Larva) has invalid modelid=12346
UPDATE creature SET modelid=0 WHERE guid=54148 AND modelid=12346;

-- GUID 54285: creature 12218 (Vile Larva) has invalid modelid=12346
UPDATE creature SET modelid=0 WHERE guid=54285 AND modelid=12346;

-- GUID 54363: creature 12218 (Vile Larva) has invalid modelid=12346
UPDATE creature SET modelid=0 WHERE guid=54363 AND modelid=12346;

-- GUID 54364: creature 12218 (Vile Larva) has invalid modelid=12346
UPDATE creature SET modelid=0 WHERE guid=54364 AND modelid=12346;

-- GUID 54365: creature 12218 (Vile Larva) has invalid modelid=12346
UPDATE creature SET modelid=0 WHERE guid=54365 AND modelid=12346;

-- GUID 54366: creature 12218 (Vile Larva) has invalid modelid=12346
UPDATE creature SET modelid=0 WHERE guid=54366 AND modelid=12346;

-- GUID 54367: creature 12218 (Vile Larva) has invalid modelid=12346
UPDATE creature SET modelid=0 WHERE guid=54367 AND modelid=12346;

-- GUID 54368: creature 12218 (Vile Larva) has invalid modelid=12346
UPDATE creature SET modelid=0 WHERE guid=54368 AND modelid=12346;

-- GUID 54369: creature 12218 (Vile Larva) has invalid modelid=12346
UPDATE creature SET modelid=0 WHERE guid=54369 AND modelid=12346;

-- GUID 54370: creature 12218 (Vile Larva) has invalid modelid=12346
UPDATE creature SET modelid=0 WHERE guid=54370 AND modelid=12346;

-- GUID 54371: creature 12218 (Vile Larva) has invalid modelid=12346
UPDATE creature SET modelid=0 WHERE guid=54371 AND modelid=12346;

-- GUID 54372: creature 12218 (Vile Larva) has invalid modelid=12346
UPDATE creature SET modelid=0 WHERE guid=54372 AND modelid=12346;

-- GUID 54373: creature 12218 (Vile Larva) has invalid modelid=12346
UPDATE creature SET modelid=0 WHERE guid=54373 AND modelid=12346;

-- GUID 54374: creature 12218 (Vile Larva) has invalid modelid=12346
UPDATE creature SET modelid=0 WHERE guid=54374 AND modelid=12346;

-- GUID 54375: creature 12218 (Vile Larva) has invalid modelid=12346
UPDATE creature SET modelid=0 WHERE guid=54375 AND modelid=12346;

-- GUID 54376: creature 12218 (Vile Larva) has invalid modelid=12346
UPDATE creature SET modelid=0 WHERE guid=54376 AND modelid=12346;

-- GUID 54377: creature 12218 (Vile Larva) has invalid modelid=12346
UPDATE creature SET modelid=0 WHERE guid=54377 AND modelid=12346;

-- GUID 54378: creature 12218 (Vile Larva) has invalid modelid=12346
UPDATE creature SET modelid=0 WHERE guid=54378 AND modelid=12346;

-- GUID 54379: creature 12218 (Vile Larva) has invalid modelid=12346
UPDATE creature SET modelid=0 WHERE guid=54379 AND modelid=12346;

-- GUID 54380: creature 12218 (Vile Larva) has invalid modelid=12346
UPDATE creature SET modelid=0 WHERE guid=54380 AND modelid=12346;

-- GUID 54391: creature 12218 (Vile Larva) has invalid modelid=12346
UPDATE creature SET modelid=0 WHERE guid=54391 AND modelid=12346;

-- GUID 54418: creature 12218 (Vile Larva) has invalid modelid=12346
UPDATE creature SET modelid=0 WHERE guid=54418 AND modelid=12346;

-- GUID 54443: creature 12218 (Vile Larva) has invalid modelid=12346
UPDATE creature SET modelid=0 WHERE guid=54443 AND modelid=12346;

-- GUID 54444: creature 12218 (Vile Larva) has invalid modelid=12346
UPDATE creature SET modelid=0 WHERE guid=54444 AND modelid=12346;

-- GUID 54446: creature 12218 (Vile Larva) has invalid modelid=12346
UPDATE creature SET modelid=0 WHERE guid=54446 AND modelid=12346;

-- GUID 54447: creature 12218 (Vile Larva) has invalid modelid=12346
UPDATE creature SET modelid=0 WHERE guid=54447 AND modelid=12346;

-- GUID 54448: creature 12218 (Vile Larva) has invalid modelid=12346
UPDATE creature SET modelid=0 WHERE guid=54448 AND modelid=12346;

-- GUID 83328: creature 14881 (Spider) has invalid modelid=14952
UPDATE creature SET modelid=0 WHERE guid=83328 AND modelid=14952;

-- GUID 91163: creature 18341 (Pandemonius) has invalid modelid=19338
UPDATE creature SET modelid=0 WHERE guid=91163 AND modelid=19338;

-- GUID 91178: creature 14881 (Spider) has invalid modelid=14952
UPDATE creature SET modelid=0 WHERE guid=91178 AND modelid=14952;

-- GUID 100165: creature 32261 (Crystal Spider) has invalid modelid=27861
UPDATE creature SET modelid=0 WHERE guid=100165 AND modelid=27861;

-- GUID 100166: creature 32261 (Crystal Spider) has invalid modelid=27861
UPDATE creature SET modelid=0 WHERE guid=100166 AND modelid=27861;

-- GUID 100167: creature 32261 (Crystal Spider) has invalid modelid=27861
UPDATE creature SET modelid=0 WHERE guid=100167 AND modelid=27861;

-- GUID 100168: creature 32261 (Crystal Spider) has invalid modelid=27861
UPDATE creature SET modelid=0 WHERE guid=100168 AND modelid=27861;

-- GUID 100169: creature 32261 (Crystal Spider) has invalid modelid=27861
UPDATE creature SET modelid=0 WHERE guid=100169 AND modelid=27861;

-- GUID 100171: creature 32261 (Crystal Spider) has invalid modelid=27861
UPDATE creature SET modelid=0 WHERE guid=100171 AND modelid=27861;

-- GUID 102226: creature 14881 (Spider) has invalid modelid=14952
UPDATE creature SET modelid=0 WHERE guid=102226 AND modelid=14952;

-- GUID 102227: creature 14881 (Spider) has invalid modelid=14952
UPDATE creature SET modelid=0 WHERE guid=102227 AND modelid=14952;

-- GUID 125986: creature 14881 (Spider) has invalid modelid=14952
UPDATE creature SET modelid=0 WHERE guid=125986 AND modelid=14952;

-- GUID 125991: creature 14881 (Spider) has invalid modelid=14952
UPDATE creature SET modelid=0 WHERE guid=125991 AND modelid=14952;

-- GUID 125992: creature 14881 (Spider) has invalid modelid=14952
UPDATE creature SET modelid=0 WHERE guid=125992 AND modelid=14952;

-- GUID 126422: creature 32261 (Crystal Spider) has invalid modelid=27861
UPDATE creature SET modelid=0 WHERE guid=126422 AND modelid=27861;

-- GUID 126423: creature 32261 (Crystal Spider) has invalid modelid=27861
UPDATE creature SET modelid=0 WHERE guid=126423 AND modelid=27861;

-- GUID 126424: creature 32261 (Crystal Spider) has invalid modelid=27861
UPDATE creature SET modelid=0 WHERE guid=126424 AND modelid=27861;

-- GUID 126425: creature 32261 (Crystal Spider) has invalid modelid=27861
UPDATE creature SET modelid=0 WHERE guid=126425 AND modelid=27861;

-- GUID 126426: creature 32261 (Crystal Spider) has invalid modelid=27861
UPDATE creature SET modelid=0 WHERE guid=126426 AND modelid=27861;

-- GUID 126427: creature 32261 (Crystal Spider) has invalid modelid=27861
UPDATE creature SET modelid=0 WHERE guid=126427 AND modelid=27861;

-- GUID 126428: creature 32261 (Crystal Spider) has invalid modelid=27861
UPDATE creature SET modelid=0 WHERE guid=126428 AND modelid=27861;

-- GUID 126429: creature 32261 (Crystal Spider) has invalid modelid=27861
UPDATE creature SET modelid=0 WHERE guid=126429 AND modelid=27861;

-- GUID 126430: creature 32261 (Crystal Spider) has invalid modelid=27861
UPDATE creature SET modelid=0 WHERE guid=126430 AND modelid=27861;

-- GUID 126431: creature 32261 (Crystal Spider) has invalid modelid=27861
UPDATE creature SET modelid=0 WHERE guid=126431 AND modelid=27861;

-- GUID 126432: creature 32261 (Crystal Spider) has invalid modelid=27861
UPDATE creature SET modelid=0 WHERE guid=126432 AND modelid=27861;

-- GUID 126433: creature 32261 (Crystal Spider) has invalid modelid=27861
UPDATE creature SET modelid=0 WHERE guid=126433 AND modelid=27861;

-- GUID 127067: creature 29829 (Drakkari Earthshaker) has invalid modelid=26590
UPDATE creature SET modelid=0 WHERE guid=127067 AND modelid=26590;

-- GUID 127068: creature 29829 (Drakkari Earthshaker) has invalid modelid=26590
UPDATE creature SET modelid=0 WHERE guid=127068 AND modelid=26590;

-- GUID 127069: creature 29829 (Drakkari Earthshaker) has invalid modelid=26590
UPDATE creature SET modelid=0 WHERE guid=127069 AND modelid=26590;

-- GUID 127070: creature 29829 (Drakkari Earthshaker) has invalid modelid=26590
UPDATE creature SET modelid=0 WHERE guid=127070 AND modelid=26590;

-- GUID 127071: creature 29830 (Living Mojo) has invalid modelid=27029
UPDATE creature SET modelid=0 WHERE guid=127071 AND modelid=27029;

-- GUID 127072: creature 29830 (Living Mojo) has invalid modelid=27029
UPDATE creature SET modelid=0 WHERE guid=127072 AND modelid=27029;

-- GUID 127073: creature 29830 (Living Mojo) has invalid modelid=27029
UPDATE creature SET modelid=0 WHERE guid=127073 AND modelid=27029;

-- GUID 127074: creature 29830 (Living Mojo) has invalid modelid=27029
UPDATE creature SET modelid=0 WHERE guid=127074 AND modelid=27029;

-- GUID 127075: creature 29830 (Living Mojo) has invalid modelid=27029
UPDATE creature SET modelid=0 WHERE guid=127075 AND modelid=27029;

-- GUID 127076: creature 29830 (Living Mojo) has invalid modelid=27029
UPDATE creature SET modelid=0 WHERE guid=127076 AND modelid=27029;

-- GUID 127077: creature 29830 (Living Mojo) has invalid modelid=27029
UPDATE creature SET modelid=0 WHERE guid=127077 AND modelid=27029;

-- GUID 127078: creature 29830 (Living Mojo) has invalid modelid=27029
UPDATE creature SET modelid=0 WHERE guid=127078 AND modelid=27029;

-- GUID 127079: creature 29830 (Living Mojo) has invalid modelid=27029
UPDATE creature SET modelid=0 WHERE guid=127079 AND modelid=27029;

-- GUID 127221: creature 14881 (Spider) has invalid modelid=14952
UPDATE creature SET modelid=0 WHERE guid=127221 AND modelid=14952;

-- GUID 127223: creature 14881 (Spider) has invalid modelid=14952
UPDATE creature SET modelid=0 WHERE guid=127223 AND modelid=14952;

-- GUID 127458: creature 14881 (Spider) has invalid modelid=14952
UPDATE creature SET modelid=0 WHERE guid=127458 AND modelid=14952;

-- GUID 127466: creature 14881 (Spider) has invalid modelid=14952
UPDATE creature SET modelid=0 WHERE guid=127466 AND modelid=14952;

-- GUID 127468: creature 14881 (Spider) has invalid modelid=14952
UPDATE creature SET modelid=0 WHERE guid=127468 AND modelid=14952;

-- GUID 127470: creature 14881 (Spider) has invalid modelid=14952
UPDATE creature SET modelid=0 WHERE guid=127470 AND modelid=14952;

-- GUID 127707: creature 14881 (Spider) has invalid modelid=14952
UPDATE creature SET modelid=0 WHERE guid=127707 AND modelid=14952;

-- GUID 127708: creature 14881 (Spider) has invalid modelid=14952
UPDATE creature SET modelid=0 WHERE guid=127708 AND modelid=14952;

-- GUID 127711: creature 14881 (Spider) has invalid modelid=14952
UPDATE creature SET modelid=0 WHERE guid=127711 AND modelid=14952;

-- GUID 127712: creature 14881 (Spider) has invalid modelid=14952
UPDATE creature SET modelid=0 WHERE guid=127712 AND modelid=14952;

-- GUID 127717: creature 14881 (Spider) has invalid modelid=14952
UPDATE creature SET modelid=0 WHERE guid=127717 AND modelid=14952;

-- GUID 127722: creature 14881 (Spider) has invalid modelid=14952
UPDATE creature SET modelid=0 WHERE guid=127722 AND modelid=14952;

-- GUID 127725: creature 14881 (Spider) has invalid modelid=14952
UPDATE creature SET modelid=0 WHERE guid=127725 AND modelid=14952;

-- GUID 127728: creature 14881 (Spider) has invalid modelid=14952
UPDATE creature SET modelid=0 WHERE guid=127728 AND modelid=14952;

-- GUID 127730: creature 14881 (Spider) has invalid modelid=14952
UPDATE creature SET modelid=0 WHERE guid=127730 AND modelid=14952;

-- GUID 127734: creature 14881 (Spider) has invalid modelid=14952
UPDATE creature SET modelid=0 WHERE guid=127734 AND modelid=14952;

-- GUID 127735: creature 14881 (Spider) has invalid modelid=14952
UPDATE creature SET modelid=0 WHERE guid=127735 AND modelid=14952;

-- GUID 127739: creature 14881 (Spider) has invalid modelid=14952
UPDATE creature SET modelid=0 WHERE guid=127739 AND modelid=14952;

-- GUID 127840: creature 16998 (Mr. Bigglesworth) has invalid modelid=16622
UPDATE creature SET modelid=0 WHERE guid=127840 AND modelid=16622;

-- GUID 127862: creature 15976 (Venom Stalker) has invalid modelid=15939
UPDATE creature SET modelid=0 WHERE guid=127862 AND modelid=15939;

-- GUID 127863: creature 15976 (Venom Stalker) has invalid modelid=15939
UPDATE creature SET modelid=0 WHERE guid=127863 AND modelid=15939;

-- GUID 127864: creature 15976 (Venom Stalker) has invalid modelid=15939
UPDATE creature SET modelid=0 WHERE guid=127864 AND modelid=15939;

-- GUID 127865: creature 15976 (Venom Stalker) has invalid modelid=15939
UPDATE creature SET modelid=0 WHERE guid=127865 AND modelid=15939;

-- GUID 127866: creature 15976 (Venom Stalker) has invalid modelid=15939
UPDATE creature SET modelid=0 WHERE guid=127866 AND modelid=15939;

-- GUID 127867: creature 15976 (Venom Stalker) has invalid modelid=15939
UPDATE creature SET modelid=0 WHERE guid=127867 AND modelid=15939;

-- GUID 127868: creature 15976 (Venom Stalker) has invalid modelid=15939
UPDATE creature SET modelid=0 WHERE guid=127868 AND modelid=15939;

-- GUID 127869: creature 15976 (Venom Stalker) has invalid modelid=15939
UPDATE creature SET modelid=0 WHERE guid=127869 AND modelid=15939;

-- GUID 127870: creature 15976 (Venom Stalker) has invalid modelid=15939
UPDATE creature SET modelid=0 WHERE guid=127870 AND modelid=15939;

-- GUID 127871: creature 15976 (Venom Stalker) has invalid modelid=15939
UPDATE creature SET modelid=0 WHERE guid=127871 AND modelid=15939;

-- GUID 127872: creature 15976 (Venom Stalker) has invalid modelid=15939
UPDATE creature SET modelid=0 WHERE guid=127872 AND modelid=15939;

-- GUID 127873: creature 15976 (Venom Stalker) has invalid modelid=15939
UPDATE creature SET modelid=0 WHERE guid=127873 AND modelid=15939;

-- GUID 127874: creature 15977 (Poisonous Skitterer) has invalid modelid=959
UPDATE creature SET modelid=0 WHERE guid=127874 AND modelid=959;

-- GUID 127875: creature 15977 (Poisonous Skitterer) has invalid modelid=959
UPDATE creature SET modelid=0 WHERE guid=127875 AND modelid=959;

-- GUID 127876: creature 15977 (Poisonous Skitterer) has invalid modelid=959
UPDATE creature SET modelid=0 WHERE guid=127876 AND modelid=959;

-- GUID 127877: creature 15977 (Poisonous Skitterer) has invalid modelid=959
UPDATE creature SET modelid=0 WHERE guid=127877 AND modelid=959;

-- GUID 127878: creature 15977 (Poisonous Skitterer) has invalid modelid=959
UPDATE creature SET modelid=0 WHERE guid=127878 AND modelid=959;

-- GUID 127879: creature 15977 (Poisonous Skitterer) has invalid modelid=959
UPDATE creature SET modelid=0 WHERE guid=127879 AND modelid=959;

-- GUID 127880: creature 15977 (Poisonous Skitterer) has invalid modelid=959
UPDATE creature SET modelid=0 WHERE guid=127880 AND modelid=959;

-- GUID 127881: creature 15977 (Poisonous Skitterer) has invalid modelid=959
UPDATE creature SET modelid=0 WHERE guid=127881 AND modelid=959;

-- GUID 127882: creature 15977 (Poisonous Skitterer) has invalid modelid=959
UPDATE creature SET modelid=0 WHERE guid=127882 AND modelid=959;

-- GUID 127883: creature 15977 (Poisonous Skitterer) has invalid modelid=959
UPDATE creature SET modelid=0 WHERE guid=127883 AND modelid=959;

-- GUID 127884: creature 15977 (Poisonous Skitterer) has invalid modelid=959
UPDATE creature SET modelid=0 WHERE guid=127884 AND modelid=959;

-- GUID 127885: creature 15977 (Poisonous Skitterer) has invalid modelid=959
UPDATE creature SET modelid=0 WHERE guid=127885 AND modelid=959;

-- GUID 127886: creature 15977 (Poisonous Skitterer) has invalid modelid=959
UPDATE creature SET modelid=0 WHERE guid=127886 AND modelid=959;

-- GUID 127887: creature 15977 (Poisonous Skitterer) has invalid modelid=959
UPDATE creature SET modelid=0 WHERE guid=127887 AND modelid=959;

-- GUID 127888: creature 15977 (Poisonous Skitterer) has invalid modelid=959
UPDATE creature SET modelid=0 WHERE guid=127888 AND modelid=959;

-- GUID 127889: creature 15977 (Poisonous Skitterer) has invalid modelid=959
UPDATE creature SET modelid=0 WHERE guid=127889 AND modelid=959;

-- GUID 127890: creature 15977 (Poisonous Skitterer) has invalid modelid=959
UPDATE creature SET modelid=0 WHERE guid=127890 AND modelid=959;

-- GUID 127891: creature 15977 (Poisonous Skitterer) has invalid modelid=959
UPDATE creature SET modelid=0 WHERE guid=127891 AND modelid=959;

-- GUID 127892: creature 15977 (Poisonous Skitterer) has invalid modelid=959
UPDATE creature SET modelid=0 WHERE guid=127892 AND modelid=959;

-- GUID 127893: creature 15977 (Poisonous Skitterer) has invalid modelid=959
UPDATE creature SET modelid=0 WHERE guid=127893 AND modelid=959;

-- GUID 127894: creature 15977 (Poisonous Skitterer) has invalid modelid=959
UPDATE creature SET modelid=0 WHERE guid=127894 AND modelid=959;

-- GUID 127895: creature 15977 (Poisonous Skitterer) has invalid modelid=959
UPDATE creature SET modelid=0 WHERE guid=127895 AND modelid=959;

-- GUID 127896: creature 15977 (Poisonous Skitterer) has invalid modelid=959
UPDATE creature SET modelid=0 WHERE guid=127896 AND modelid=959;

-- GUID 127897: creature 15977 (Poisonous Skitterer) has invalid modelid=959
UPDATE creature SET modelid=0 WHERE guid=127897 AND modelid=959;

-- GUID 127898: creature 15977 (Poisonous Skitterer) has invalid modelid=959
UPDATE creature SET modelid=0 WHERE guid=127898 AND modelid=959;

-- GUID 127899: creature 15977 (Poisonous Skitterer) has invalid modelid=959
UPDATE creature SET modelid=0 WHERE guid=127899 AND modelid=959;

-- GUID 127900: creature 15977 (Poisonous Skitterer) has invalid modelid=959
UPDATE creature SET modelid=0 WHERE guid=127900 AND modelid=959;

-- GUID 127901: creature 15977 (Poisonous Skitterer) has invalid modelid=959
UPDATE creature SET modelid=0 WHERE guid=127901 AND modelid=959;

-- GUID 127902: creature 15977 (Poisonous Skitterer) has invalid modelid=959
UPDATE creature SET modelid=0 WHERE guid=127902 AND modelid=959;

-- GUID 127903: creature 15977 (Poisonous Skitterer) has invalid modelid=959
UPDATE creature SET modelid=0 WHERE guid=127903 AND modelid=959;

-- GUID 127904: creature 15977 (Poisonous Skitterer) has invalid modelid=959
UPDATE creature SET modelid=0 WHERE guid=127904 AND modelid=959;

-- GUID 127905: creature 15977 (Poisonous Skitterer) has invalid modelid=959
UPDATE creature SET modelid=0 WHERE guid=127905 AND modelid=959;

-- GUID 127906: creature 15977 (Poisonous Skitterer) has invalid modelid=959
UPDATE creature SET modelid=0 WHERE guid=127906 AND modelid=959;

-- GUID 127907: creature 15977 (Poisonous Skitterer) has invalid modelid=959
UPDATE creature SET modelid=0 WHERE guid=127907 AND modelid=959;

-- GUID 127915: creature 15977 (Poisonous Skitterer) has invalid modelid=959
UPDATE creature SET modelid=0 WHERE guid=127915 AND modelid=959;

-- GUID 127923: creature 15977 (Poisonous Skitterer) has invalid modelid=959
UPDATE creature SET modelid=0 WHERE guid=127923 AND modelid=959;

-- GUID 127931: creature 15977 (Poisonous Skitterer) has invalid modelid=959
UPDATE creature SET modelid=0 WHERE guid=127931 AND modelid=959;

-- GUID 127932: creature 15977 (Poisonous Skitterer) has invalid modelid=959
UPDATE creature SET modelid=0 WHERE guid=127932 AND modelid=959;

-- GUID 127933: creature 15977 (Poisonous Skitterer) has invalid modelid=959
UPDATE creature SET modelid=0 WHERE guid=127933 AND modelid=959;

-- GUID 127934: creature 15977 (Poisonous Skitterer) has invalid modelid=959
UPDATE creature SET modelid=0 WHERE guid=127934 AND modelid=959;

-- GUID 127935: creature 15977 (Poisonous Skitterer) has invalid modelid=959
UPDATE creature SET modelid=0 WHERE guid=127935 AND modelid=959;

-- GUID 127936: creature 15977 (Poisonous Skitterer) has invalid modelid=959
UPDATE creature SET modelid=0 WHERE guid=127936 AND modelid=959;

-- GUID 127937: creature 15977 (Poisonous Skitterer) has invalid modelid=959
UPDATE creature SET modelid=0 WHERE guid=127937 AND modelid=959;

-- GUID 127938: creature 15977 (Poisonous Skitterer) has invalid modelid=959
UPDATE creature SET modelid=0 WHERE guid=127938 AND modelid=959;

-- GUID 127939: creature 15977 (Poisonous Skitterer) has invalid modelid=959
UPDATE creature SET modelid=0 WHERE guid=127939 AND modelid=959;

-- GUID 127940: creature 15977 (Poisonous Skitterer) has invalid modelid=959
UPDATE creature SET modelid=0 WHERE guid=127940 AND modelid=959;

-- GUID 127941: creature 15977 (Poisonous Skitterer) has invalid modelid=959
UPDATE creature SET modelid=0 WHERE guid=127941 AND modelid=959;

-- GUID 127942: creature 15977 (Poisonous Skitterer) has invalid modelid=959
UPDATE creature SET modelid=0 WHERE guid=127942 AND modelid=959;

-- GUID 127943: creature 15977 (Poisonous Skitterer) has invalid modelid=959
UPDATE creature SET modelid=0 WHERE guid=127943 AND modelid=959;

-- GUID 127944: creature 15977 (Poisonous Skitterer) has invalid modelid=959
UPDATE creature SET modelid=0 WHERE guid=127944 AND modelid=959;

-- GUID 127945: creature 15977 (Poisonous Skitterer) has invalid modelid=959
UPDATE creature SET modelid=0 WHERE guid=127945 AND modelid=959;

-- GUID 127946: creature 15977 (Poisonous Skitterer) has invalid modelid=959
UPDATE creature SET modelid=0 WHERE guid=127946 AND modelid=959;

-- GUID 127947: creature 15977 (Poisonous Skitterer) has invalid modelid=959
UPDATE creature SET modelid=0 WHERE guid=127947 AND modelid=959;

-- GUID 127948: creature 15977 (Poisonous Skitterer) has invalid modelid=959
UPDATE creature SET modelid=0 WHERE guid=127948 AND modelid=959;

-- GUID 127949: creature 15977 (Poisonous Skitterer) has invalid modelid=959
UPDATE creature SET modelid=0 WHERE guid=127949 AND modelid=959;

-- GUID 127950: creature 15977 (Poisonous Skitterer) has invalid modelid=959
UPDATE creature SET modelid=0 WHERE guid=127950 AND modelid=959;

-- GUID 127951: creature 15977 (Poisonous Skitterer) has invalid modelid=959
UPDATE creature SET modelid=0 WHERE guid=127951 AND modelid=959;

-- GUID 127952: creature 15977 (Poisonous Skitterer) has invalid modelid=959
UPDATE creature SET modelid=0 WHERE guid=127952 AND modelid=959;

-- GUID 127953: creature 15977 (Poisonous Skitterer) has invalid modelid=959
UPDATE creature SET modelid=0 WHERE guid=127953 AND modelid=959;

-- GUID 127954: creature 15977 (Poisonous Skitterer) has invalid modelid=959
UPDATE creature SET modelid=0 WHERE guid=127954 AND modelid=959;

-- GUID 127955: creature 15977 (Poisonous Skitterer) has invalid modelid=959
UPDATE creature SET modelid=0 WHERE guid=127955 AND modelid=959;

-- GUID 127956: creature 15977 (Poisonous Skitterer) has invalid modelid=959
UPDATE creature SET modelid=0 WHERE guid=127956 AND modelid=959;

-- GUID 127957: creature 15977 (Poisonous Skitterer) has invalid modelid=959
UPDATE creature SET modelid=0 WHERE guid=127957 AND modelid=959;

-- GUID 127958: creature 15977 (Poisonous Skitterer) has invalid modelid=959
UPDATE creature SET modelid=0 WHERE guid=127958 AND modelid=959;

-- GUID 127959: creature 15977 (Poisonous Skitterer) has invalid modelid=959
UPDATE creature SET modelid=0 WHERE guid=127959 AND modelid=959;

-- GUID 127960: creature 15977 (Poisonous Skitterer) has invalid modelid=959
UPDATE creature SET modelid=0 WHERE guid=127960 AND modelid=959;

-- GUID 127963: creature 15977 (Poisonous Skitterer) has invalid modelid=959
UPDATE creature SET modelid=0 WHERE guid=127963 AND modelid=959;

-- GUID 127971: creature 15977 (Poisonous Skitterer) has invalid modelid=959
UPDATE creature SET modelid=0 WHERE guid=127971 AND modelid=959;

-- GUID 131844: creature 14881 (Spider) has invalid modelid=14952
UPDATE creature SET modelid=0 WHERE guid=131844 AND modelid=14952;

-- GUID 131854: creature 14881 (Spider) has invalid modelid=14952
UPDATE creature SET modelid=0 WHERE guid=131854 AND modelid=14952;

-- GUID 132324: creature 27911 (Nell) has invalid modelid=24922
UPDATE creature SET modelid=0 WHERE guid=132324 AND modelid=24922;

-- GUID 132349: creature 27912 (Pepper) has invalid modelid=24923
UPDATE creature SET modelid=0 WHERE guid=132349 AND modelid=24923;

-- GUID 132370: creature 14881 (Spider) has invalid modelid=14952
UPDATE creature SET modelid=0 WHERE guid=132370 AND modelid=14952;

-- GUID 132371: creature 14881 (Spider) has invalid modelid=14952
UPDATE creature SET modelid=0 WHERE guid=132371 AND modelid=14952;

-- GUID 135326: creature 14881 (Spider) has invalid modelid=14952
UPDATE creature SET modelid=0 WHERE guid=135326 AND modelid=14952;

-- GUID 135331: creature 14881 (Spider) has invalid modelid=14952
UPDATE creature SET modelid=0 WHERE guid=135331 AND modelid=14952;

-- GUID 135334: creature 14881 (Spider) has invalid modelid=14952
UPDATE creature SET modelid=0 WHERE guid=135334 AND modelid=14952;

-- GUID 135343: creature 14881 (Spider) has invalid modelid=14952
UPDATE creature SET modelid=0 WHERE guid=135343 AND modelid=14952;

-- GUID 135382: creature 16170 (Coldmist Stalker) has invalid modelid=16051
UPDATE creature SET modelid=0 WHERE guid=135382 AND modelid=16051;

-- GUID 135383: creature 16170 (Coldmist Stalker) has invalid modelid=16051
UPDATE creature SET modelid=0 WHERE guid=135383 AND modelid=16051;

-- GUID 135385: creature 16170 (Coldmist Stalker) has invalid modelid=16051
UPDATE creature SET modelid=0 WHERE guid=135385 AND modelid=16051;

-- GUID 135386: creature 16170 (Coldmist Stalker) has invalid modelid=16051
UPDATE creature SET modelid=0 WHERE guid=135386 AND modelid=16051;

-- GUID 135387: creature 16170 (Coldmist Stalker) has invalid modelid=16051
UPDATE creature SET modelid=0 WHERE guid=135387 AND modelid=16051;

-- GUID 135388: creature 16170 (Coldmist Stalker) has invalid modelid=16051
UPDATE creature SET modelid=0 WHERE guid=135388 AND modelid=16051;

-- GUID 135389: creature 16170 (Coldmist Stalker) has invalid modelid=16051
UPDATE creature SET modelid=0 WHERE guid=135389 AND modelid=16051;

-- GUID 135390: creature 16170 (Coldmist Stalker) has invalid modelid=16051
UPDATE creature SET modelid=0 WHERE guid=135390 AND modelid=16051;

-- GUID 135391: creature 16170 (Coldmist Stalker) has invalid modelid=16051
UPDATE creature SET modelid=0 WHERE guid=135391 AND modelid=16051;

-- GUID 135392: creature 16170 (Coldmist Stalker) has invalid modelid=16051
UPDATE creature SET modelid=0 WHERE guid=135392 AND modelid=16051;

-- GUID 201955: creature 14881 (Spider) has invalid modelid=14952
UPDATE creature SET modelid=0 WHERE guid=201955 AND modelid=14952;

-- GUID 202115: creature 14881 (Spider) has invalid modelid=14952
UPDATE creature SET modelid=0 WHERE guid=202115 AND modelid=14952;

-- GUID 375674: creature 46260 (Searing Destroyer) has invalid modelid=1405
UPDATE creature SET modelid=0 WHERE guid=375674 AND modelid=1405;

-- GUID 375703: creature 46260 (Searing Destroyer) has invalid modelid=1405
UPDATE creature SET modelid=0 WHERE guid=375703 AND modelid=1405;

-- GUID 375734: creature 46260 (Searing Destroyer) has invalid modelid=1405
UPDATE creature SET modelid=0 WHERE guid=375734 AND modelid=1405;

-- GUID 375736: creature 46260 (Searing Destroyer) has invalid modelid=1405
UPDATE creature SET modelid=0 WHERE guid=375736 AND modelid=1405;

-- GUID 375740: creature 46260 (Searing Destroyer) has invalid modelid=1405
UPDATE creature SET modelid=0 WHERE guid=375740 AND modelid=1405;

-- GUID 375743: creature 46260 (Searing Destroyer) has invalid modelid=1405
UPDATE creature SET modelid=0 WHERE guid=375743 AND modelid=1405;

-- GUID 3000005891: creature 65325 (Puntable Marmot) has invalid modelid=43877
UPDATE creature SET modelid=0 WHERE guid=3000005891 AND modelid=43877;

-- Total fix statements: 232
