-- ==========================================================================
-- Empty Service Flag Fixes
-- Generated by audit_empty_services.py
-- 
-- Removes vendor/trainer flags from NPCs that clearly should not have them.
-- Conservative: only removes from wrong-type, test/debug, or Wowhead-confirmed
-- non-vendor/non-trainer NPCs.
-- ==========================================================================

-- -------------------------------------------------------
-- Remove vendor flag (npcflag & ~128) - 14 NPCs
-- -------------------------------------------------------
USE `world`;
-- WRONG TYPE - Creature type doesn't match service role
UPDATE creature_template SET npcflag = npcflag & ~128 WHERE entry = 255203; -- Xiao Dan -- Decor Vendor type=Wild Pet wh_roles=['vendor']
UPDATE creature_template SET npcflag = npcflag & ~128 WHERE entry = 255213; -- Faarden the Builder -- Decor Vendor type=Wild Pet wh_roles=['vendor']
UPDATE creature_template SET npcflag = npcflag & ~128 WHERE entry = 255216; -- Balen Starfinder -- Decor Vendor type=Wild Pet wh_roles=['vendor']
UPDATE creature_template SET npcflag = npcflag & ~128 WHERE entry = 255218; -- Argan Hammerfist -- Decor Vendor type=Wild Pet wh_roles=['vendor']
UPDATE creature_template SET npcflag = npcflag & ~128 WHERE entry = 255221; -- Trevor Grenner -- Decor Vendor type=Wild Pet wh_roles=['vendor']
UPDATE creature_template SET npcflag = npcflag & ~128 WHERE entry = 255278; -- Gronthul -- Decor Vendor type=Wild Pet wh_roles=['vendor']
UPDATE creature_template SET npcflag = npcflag & ~128 WHERE entry = 255297; -- Shon'ja -- Decor Vendor type=Wild Pet wh_roles=['vendor']
UPDATE creature_template SET npcflag = npcflag & ~128 WHERE entry = 255298; -- Jehzar Starfall -- Decor Vendor type=Wild Pet wh_roles=['vendor']
UPDATE creature_template SET npcflag = npcflag & ~128 WHERE entry = 255299; -- Lefton Farrer -- Decor Vendor type=Wild Pet wh_roles=['vendor']
UPDATE creature_template SET npcflag = npcflag & ~128 WHERE entry = 255301; -- Botanist Boh'an -- Decor Vendor type=Wild Pet wh_roles=['vendor']

-- TEST/DEBUG - Name indicates test or unused NPC
UPDATE creature_template SET npcflag = npcflag & ~128 WHERE entry = 3559; -- Temp Poisoning Vendor Dwarf -- Poison Supplies type=Humanoid wh_roles=['vendor']
UPDATE creature_template SET npcflag = npcflag & ~128 WHERE entry = 3564; -- Temp Reagent Vendor Dwarf -- Reagents type=Humanoid wh_roles=['vendor']
UPDATE creature_template SET npcflag = npcflag & ~128 WHERE entry = 85702; -- Rare Goods Vendor Test -- Rare Goods Vendor type=Humanoid wh_roles=['vendor']
UPDATE creature_template SET npcflag = npcflag & ~128 WHERE entry = 120465; -- Arne's Vendor Test -- NPC Vendor type=None wh_roles=['vendor']

-- -------------------------------------------------------
-- Remove trainer flag (npcflag & ~16) - 7 NPCs
-- -------------------------------------------------------

-- FLAG INCORRECT - Wowhead has roles but not this one
UPDATE creature_template SET npcflag = npcflag & ~16 WHERE entry = 3008; -- Mak -- Leatherworking Supplies type=Humanoid wh_roles=['vendor']
UPDATE creature_template SET npcflag = npcflag & ~16 WHERE entry = 194211; -- Hamma the Butcher -- Food & Drink type=Humanoid wh_roles=['vendor']

-- NO EVIDENCE - No subtitle, no Wowhead data
UPDATE creature_template SET npcflag = npcflag & ~16 WHERE entry = 16621; -- Ileda type=Humanoid
UPDATE creature_template SET npcflag = npcflag & ~16 WHERE entry = 16773; -- Handiir type=Humanoid
UPDATE creature_template SET npcflag = npcflag & ~16 WHERE entry = 17005; -- Duelist Larenis type=Humanoid
UPDATE creature_template SET npcflag = npcflag & ~16 WHERE entry = 202934; -- Zaqali Forge Virtuoso type=Humanoid

-- WRONG TYPE - Creature type doesn't match service role
UPDATE creature_template SET npcflag = npcflag & ~16 WHERE entry = 79179; -- Squirt -- Wandering Trainer type=Non-combat Pet wh_roles=['trainer']


-- Total fixes: 21
